---
- hosts: aws
  connection: ssh
  gather_facts: yes
  remote_user: ansi-admin
  become: yes
  become_user: root

  tasks:
    - name: Creating user on all operating systems
      user:
       name: "{{ item }}"
       state: present
      loop: "{{ names }}"

#    - name: copy a file to only to rhel6 server
#      synchronize:
#               src: /root/tttt
#               dest: /tmp
#      when: ansible_facts['ansible_distribution_version'] == "6.9"
    - name:     
